on:
  release:
    types:
      - published

env:
  CACHE_ON_FAILURE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.90.0

      - name: Install compile-time dependencies
        uses: syndelis/cache-apt-pkgs-action@f3b6f83
        with:
          packages: libwayland-dev
          version: 1.0

      - name: Compile watershot
        shell: bash
        run: cargo build --locked --release

      - name: Attach to Release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./target/release/watershot

